"""Reproducibility / provenance helpers.

Empirical work is only credible if it can be re-run. These helpers turn a
:class:`RunResult` into (a) a typed :class:`Provenance` envelope - the runtime
identity that produced it — and (b) a self-contained, re-runnable ``.do`` script
header that pins the Stata ``version`` and (optionally) the RNG seed.

Both are pure functions over an already-produced ``RunResult`` plus the original
code; nothing here touches Stata, so the module is fully unit-testable.
"""

from __future__ import annotations

import re

from stata_code.core.schema import Provenance, RunResult

_VERSION_MAJOR_RE = re.compile(r"^\s*(\d+)")


def _stata_code_version() -> str | None:
    """Best-effort package version without a hard import cycle.

    Prefer the source ``__version__`` literal (always reflects the running
    code) over ``importlib.metadata`` (which lags in editable installs).
    """
    try:
        import stata_code

        v = getattr(stata_code, "__version__", None)
        if v:
            return str(v)
    except Exception:  # noqa: BLE001
        pass
    try:
        from importlib.metadata import PackageNotFoundError, version

        try:
            return version("stata-code")
        except PackageNotFoundError:
            return None
    except Exception:  # noqa: BLE001
        return None


def _version_floor(stata_version: str | None) -> str | None:
    """Map ``"18.0"`` to ``"18"`` for a Stata ``version`` control line."""
    if not stata_version:
        return None
    m = _VERSION_MAJOR_RE.match(stata_version)
    return m.group(1) if m else None


def build_provenance(result: RunResult, *, seed: int | None = None) -> Provenance:
    """Derive a :class:`Provenance` envelope from a finished ``RunResult``.

    ``seed`` is accepted explicitly because the RNG seed is not part of the
    result envelope; pass it when the caller set one (``set seed <n>``).
    The estimation command, when present, is read from the typed estimation
    contract or ``e(cmd)``.
    """
    command: str | None = None
    if result.results.estimation is not None:
        command = result.results.estimation.command
    if command is None:
        command = result.results.e.macros.get("cmd") or result.results.last_estimation_cmd

    return Provenance(
        stata_version=result.stata.version,
        stata_edition=result.stata.edition,
        stata_code_version=_stata_code_version(),
        schema_version=result.schema_version,
        backend=result.stata.backend,
        generated_at=result.started_at,
        command=command,
        seed=seed,
    )


def build_reproducible_do(
    result: RunResult,
    code: str,
    *,
    seed: int | None = None,
    clear_all: bool = False,
    set_more_off: bool = True,
) -> str:
    """Compose a self-contained, re-runnable ``.do`` script for ``code``.

    The header pins Stata's ``version`` (so the code runs under the same
    language semantics it was authored against) and, when ``seed`` is given,
    re-sets the RNG. ``code`` is emitted verbatim — the caller owns its
    correctness; this only wraps it with a reproducibility preamble.

    ``clear_all`` (default off) prepends ``clear all`` for a cold-start script;
    leave it off when ``code`` manages its own dataset state.
    """
    prov = build_provenance(result, seed=seed)
    lines: list[str] = []

    tag = prov.stata_code_version or "stata-code"
    lines.append(f"*! Reproducible Stata script - generated by stata-code {tag}")
    if prov.generated_at:
        lines.append(f"*! Generated: {prov.generated_at}")
    edition = (
        prov.stata_edition.value
        if prov.stata_edition is not None and prov.stata_edition.value != "unknown"
        else ""
    )
    ver_desc = " ".join(p for p in [prov.stata_version, edition] if p) or "unknown"
    lines.append(f"*! Stata: {ver_desc} / result schema {prov.schema_version}")
    lines.append("")

    version_floor = _version_floor(prov.stata_version)
    if version_floor:
        lines.append(f"version {version_floor}")
    if clear_all:
        lines.append("clear all")
    if set_more_off:
        lines.append("set more off")
    if seed is not None:
        lines.append(f"set seed {seed}")
    if version_floor or clear_all or set_more_off or seed is not None:
        lines.append("")

    lines.append(code.rstrip("\n"))
    lines.append("")  # trailing newline
    return "\n".join(lines)
