"""Tests for reproducibility / provenance helpers."""

from __future__ import annotations

from stata_code.core.provenance import (
    _version_floor,
    build_provenance,
    build_reproducible_do,
)
from stata_code.core.schema import (
    Backend,
    EstimationResult,
    ResultsInfo,
    RunResult,
    StataEdition,
    StataInfo,
    StataReturns,
)


def _result() -> RunResult:
    return RunResult(
        ok=True,
        rc=0,
        session_id="main",
        request_id="prov-1",
        started_at="2026-06-23T19:00:00.000Z",
        elapsed_ms=10,
        stata=StataInfo(version="18.0", edition=StataEdition.MP, backend=Backend.PYSTATA),
        results=ResultsInfo(
            e=StataReturns(macros={"cmd": "regress"}),
            last_estimation_cmd="regress",
            estimation=EstimationResult(command="reghdfe", depvar="price"),
        ),
    )


def test_build_provenance_prefers_typed_estimation_command() -> None:
    prov = build_provenance(_result(), seed=12345)

    assert prov.stata_version == "18.0"
    assert prov.stata_edition is StataEdition.MP
    assert prov.backend is Backend.PYSTATA
    assert prov.generated_at == "2026-06-23T19:00:00.000Z"
    assert prov.command == "reghdfe"
    assert prov.seed == 12345


def test_build_reproducible_do_pins_runtime_and_preserves_code() -> None:
    script = build_reproducible_do(
        _result(),
        "sysuse auto, clear\nregress price mpg",
        seed=777,
        clear_all=True,
    )

    assert script.startswith("*! Reproducible Stata script - generated by stata-code")
    assert "*! Generated: 2026-06-23T19:00:00.000Z" in script
    assert "*! Stata: 18.0 MP / result schema 1.0" in script
    assert "version 18\n" in script
    assert "clear all\n" in script
    assert "set more off\n" in script
    assert "set seed 777\n" in script
    assert script.endswith("sysuse auto, clear\nregress price mpg\n")


def test_version_floor() -> None:
    assert _version_floor("18.0") == "18"
    assert _version_floor("Stata 19") is None
    assert _version_floor(None) is None


def test_public_exports_include_provenance_helpers() -> None:
    import stata_code

    assert stata_code.Provenance is not None
    assert stata_code.build_provenance is build_provenance
    assert stata_code.build_reproducible_do is build_reproducible_do
