import { strict as assert } from "node:assert";
import * as fs from "node:fs";
import * as path from "node:path";
import { describe, test } from "node:test";

import { compileFilter, DtaFilterError } from "./dtaFilter";
import { BufferByteSource, DtaReader } from "./dtaReader";

const FIXTURES = path.join(__dirname, "..", "test-fixtures", "dta");

async function open(name: string): Promise<DtaReader> {
  const bytes = new Uint8Array(fs.readFileSync(path.join(FIXTURES, name)));
  return DtaReader.open(new BufferByteSource(bytes));
}

async function count(reader: DtaReader, expression: string): Promise<number> {
  const filter = compileFilter(expression, reader.meta);
  await filter.prepare?.(reader);
  let kept = 0;
  if (filter.columns.length === 0) {
    for (let obs = 1; obs <= reader.meta.nObs; obs++) if (filter.test([], obs)) kept += 1;
    return kept;
  }
  await reader.scan(filter.columns, (rows, start) => {
    rows.forEach((row, i) => {
      if (filter.test(row, start + i + 1)) kept += 1;
    });
  });
  return kept;
}

// Each pair is [`count if <expression>` as Stata 18 reports it on
// survey118.dta, expression]. Generated by the loop in make_fixtures.do's
// companion run; see the header of dtaFilter.ts for the semantics exercised.
const STATA_COUNTS: Array<[number, string]> = [
  [158, "age > 60"], // includes the 17 missing ages: missing > every number
  [17, "age >= ."],
  [5, "age == .a"],
  [17, "missing(age)"],
  [462, "!missing(age, income)"],
  [45, "age < 30 & female == 1"],
  [108, "age < 30 | score > 90"],
  [142, 'region == "South":regionlbl'],
  [232, "inlist(region, 1, 3)"],
  [200, 'inlist(city, "Boston", "北京")'],
  [87, "inrange(age, 30, 40)"],
  [67, "inrange(age, ., 25)"],
  [90, "inrange(income, 50000, .)"],
  [100, 'city == ""'],
  [100, 'city != "" & city < "N"'],
  [200, 'strpos(city, "ost") > 0'],
  [200, 'lower(city) == "boston"'],
  [200, 'regexm(city, "^[Bb]o")'],
  [207, "income / 1000 > wage * 2"],
  [126, "-score > 50"],
  [71, "mod(id, 7) == 0"],
  [15, "_n <= 10 | _n > 495"],
  [199, "joined >= mdy(1, 1, 2020)"],
  [199, "joined >= td(01jan2020)"],
  [257, "female"],
  [500, "age"], // nonzero, including missing, is true
  [243, "!female"],
  [181, "~(age > 40) & region != .a"],
  [57, "abs(score) <= 10"],
  [500, "age + . == ."],
  [29, "round(wage) == 10"],
  [85, "floor(income / 10000) == 2"],
  [300, "strlen(city) == 6"], // bytes: 北京 is 6 bytes in UTF-8
  [100, "length(city) > 6"],
  [200, 'upper(city) == "BOSTON"'],
  [17, "int(wage) == 7"],
  [247, "region > 2"],
  [479, "income != ."],
  [280, "(age > 50 | age < 25) & !missing(income)"],
  [100, 'city > "boston"'],
  [300, 'strmatch(city, "*o*")'],
  [17, "ceil(wage) == 25"],
  [404, "min(age, 30) == 30"],
  [274, "max(score, 0) == 0"],
  [100, 'substr(city, 1, 3) == "New"'],
  [10, "age == 18 + 2 * 3"],
  [3, "2 ^ 3 == 8 & id < 4"],
  [262, "region == 1 == female"],
];

describe("compileFilter agrees with Stata's `count if`", () => {
  for (const [expected, expression] of STATA_COUNTS) {
    test(expression, async () => {
      assert.equal(await count(await open("survey118.dta"), expression), expected);
    });
  }
});

describe("compileFilter conveniences", () => {
  test("accepts a leading `if` and compound double quotes", async () => {
    const reader = await open("survey118.dta");
    assert.equal(await count(reader, "if age > 60"), 158);
    assert.equal(await count(reader, "city == `\"Boston\"'"), 100);
  });

  test("a single = is read as ==, as Stata does", async () => {
    assert.equal(await count(await open("survey118.dta"), "female = 1"), 257);
  });

  test("reads only the columns the expression names", async () => {
    const reader = await open("survey118.dta");
    const filter = compileFilter("age > 30 & city == \"Boston\" & age < 50", reader.meta);
    assert.deepEqual(
      filter.columns.map((c) => reader.meta.variables[c].name),
      ["age", "city"],
    );
    assert.deepEqual(compileFilter("_n < 5", reader.meta).columns, []);
  });

  test("a value-label text that the label does not define matches nothing", async () => {
    assert.equal(await count(await open("survey118.dta"), 'region == "Nowhere":regionlbl'), 0);
  });

  test("a label on an extended missing value resolves to that missing value", async () => {
    assert.equal(await count(await open("survey118.dta"), 'region == "Refused":regionlbl'), 9);
  });
});

describe("compileFilter errors read like Stata's", () => {
  const cases: Array<[string, RegExp]> = [
    ["city > 5", /type mismatch/],
    ['age == "x"', /type mismatch/],
    ["city", /type mismatch/],
    ["nosuch == 1", /nosuch not found/],
    ["age >", /invalid syntax/],
    ["(age > 3", /invalid syntax/],
    ["age > 3)", /invalid syntax/],
    ["age # 3", /invalid syntax/],
    ['city == "open', /unterminated string/],
    ["", /empty expression/],
    ["frobnicate(age)", /unknown function frobnicate\(\)/],
    ["inrange(age, 1)", /wrong number of arguments/],
    ['age == "x":nolabel', /value label nolabel not found/],
    ["td(yesterday) > joined", /not a date/],
  ];
  for (const [expression, message] of cases) {
    test(JSON.stringify(expression), async () => {
      const reader = await open("survey118.dta");
      assert.throws(() => compileFilter(expression, reader.meta), (err: unknown) => {
        assert.ok(err instanceof DtaFilterError);
        assert.match(err.message, message);
        return true;
      });
    });
  }

  test("an invalid regular expression is reported, not thrown raw", async () => {
    const reader = await open("survey118.dta");
    await assert.rejects(count(reader, 'regexm(city, "(")'), DtaFilterError);
  });

  test("cannot reach object internals through a function name", async () => {
    const reader = await open("survey118.dta");
    for (const name of ["constructor", "toString", "__proto__", "hasOwnProperty"]) {
      assert.throws(() => compileFilter(`${name}(age)`, reader.meta), /unknown function/);
    }
  });
});

// `count if <expression>` as Stata 18 reports it on panel118.dta (xtset firm
// year, with gaps, saved in shuffled row order) and on ts118.dta (tsset t,
// delta(2)); generated by the section of make_fixtures.do that builds them.
const PANEL_COUNTS: Array<[number, string]> = [
  [123, "L.sales > 100"], // includes the rows whose lag is missing or absent
  [123, "l.sales > 100"],
  [103, "L.sales < 100"],
  [42, "missing(L.sales)"],
  [100, "L2.sales < sales"],
  [137, "F.sales > sales"],
  [147, "D.sales > 0"],
  [79, "D.sales < 0"],
  [50, "missing(D.sales)"],
  [152, "D2.sales > 0"],
  [158, "S2.sales > 0"],
  [65, "LD.sales < 0"],
  [65, "DL.sales < 0"],
  [158, "L2D.sales > 0"],
  [56, "F2.sales == ."],
  [49, "L.growth_flag == 1 & growth_flag == 0"],
  [3, "L.sales == .a"], // a plain lag keeps the extended missing value
  [81, "L.gro == 1"], // abbreviation of growth_flag
  [96, "gro == 1"],
  [126, "sales_i > 100"],
  [123, "year > 2005 & D.sales_index == 1"],
  [111, "L0.sales > 100"],
  [111, "FL.sales > 100"],
  [158, "l2.sales + f.sales > 200"],
  [147, "S.sales > 0"],
  [145, "L3.sales > 100"],
];

const SERIES_COUNTS: Array<[number, string]> = [
  [17, "L.y < y"],
  [3, "missing(L.y)"],
  [20, "D.y > 0"],
  [22, "F.y > 0"],
  [23, "L2.y > 0"],
  [5, "missing(L2.y)"],
];

describe("time-series operators and abbreviations", () => {
  test("the tsset declaration is read from the file", async () => {
    assert.deepEqual((await open("panel118.dta")).meta.tsset, {
      timeVar: "year",
      panelVar: "firm",
      delta: 1,
    });
    assert.deepEqual((await open("ts118.dta")).meta.tsset, { timeVar: "t", panelVar: "", delta: 2 });
    assert.equal((await open("survey118.dta")).meta.tsset, undefined);
  });

  for (const [expected, expression] of PANEL_COUNTS) {
    test(`panel: count if ${expression}`, async () => {
      assert.equal(await count(await open("panel118.dta"), expression), expected);
    });
  }

  for (const [expected, expression] of SERIES_COUNTS) {
    test(`delta(2) series: count if ${expression}`, async () => {
      assert.equal(await count(await open("ts118.dta"), expression), expected);
    });
  }

  test("errors read as Stata's do", async () => {
    const panel = (await open("panel118.dta")).meta;
    assert.throws(() => compileFilter("L.sal > 100", panel), /sal ambiguous abbreviation/);
    assert.throws(() => compileFilter("sal > 100", panel), /sal ambiguous abbreviation/);
    assert.throws(() => compileFilter("L.nothere > 1", panel), /nothere not found/);
    assert.throws(() => compileFilter("L.code == 1", panel), /type mismatch/);
    const survey = (await open("survey118.dta")).meta;
    assert.throws(() => compileFilter("L.age > 1", survey), /time variable not set/);
  });

  test("an exact name wins over a longer one it abbreviates", async () => {
    // `sales` is both a variable and a prefix of `sales_index`
    const reader = await open("panel118.dta");
    assert.equal(await count(reader, "sales > 100"), await count(reader, "sales > 100 & sales_index > 0"));
  });

  test("a variable that merely looks like an operator still works", async () => {
    const reader = await open("survey118.dta");
    assert.equal(await count(reader, "id > 0"), 500);
    assert.equal(await count(reader, "id > 0 & .a > 1"), 500);
  });
});
